# Generated by Django 5.2.1 on 2025-05-13 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de descrição')),
                ('imagem', models.ImageField(upload_to='imgPostagens/', verbose_name='Imagem')),
                ('dataPublicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('curtidas', models.IntegerField(default=0, verbose_name='Curtidas')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
    ]
