# Generated by Django 5.2.7 on 2025-10-27 15:18

import api.models.arquivo
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tec", "Tecnologia"),
                            ("mat", "Matéria"),
                            ("per", "Período"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "imagemPerfil",
                    models.ImageField(
                        null=True,
                        upload_to="usuarios/%Y/%m/%d/",
                        verbose_name="Imagem de perfil",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/%Y/%m/%d/",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "linkedinUrl",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn URL"),
                ),
                (
                    "escolaFormacao",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Escola de formação",
                    ),
                ),
                (
                    "instituicaoAtual",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Instituição atual",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Criado em"
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("mod", "moderador"),
                            ("int", "internauta"),
                            ("adm", "administrador"),
                        ],
                        null=True,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "segue",
                    models.ManyToManyField(
                        blank=True,
                        related_name="seguido_por",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Segue",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Comunidade",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="comunidade_imagens/",
                        verbose_name="Imagem",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "anoFundacao",
                    models.DateField(default=2025, verbose_name="Ano de fundação"),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="banners/%Y/%m/%d/",
                        verbose_name="Banner",
                    ),
                ),
                (
                    "coordenacao",
                    models.CharField(max_length=50, verbose_name="Coordenação"),
                ),
                (
                    "seguidores",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comunidades_que_sigo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="seguidores",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunidades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Postagem",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "texto",
                    models.CharField(max_length=200, verbose_name="Texto de descrição"),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="imgPostagens/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "dataPublicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de publicação"
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        to="api.categoria", verbose_name="Categorias"
                    ),
                ),
                (
                    "comunidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.comunidade",
                        verbose_name="Comunidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postagens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Postagem",
                "verbose_name_plural": "Postagens",
            },
        ),
        migrations.CreateModel(
            name="Curtida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_curtida",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "postagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postagem_curtida",
                        to="api.postagem",
                        verbose_name="Postagem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("conteudo", models.TextField()),
                ("dataPostagem", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "postagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.postagem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repositorio",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "dataPublicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de publicação"
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, to="api.categoria", verbose_name="Categorias"
                    ),
                ),
                (
                    "comunidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.comunidade",
                        verbose_name="Comunidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositorios",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repositorio",
                "verbose_name_plural": "Repositorios",
            },
        ),
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataDenuncia", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ling", "Linguajar Ofensivo"),
                            ("spam", "Spam"),
                            ("dis", "Discurso violento"),
                            ("odio", "Ódio"),
                            ("out", "Outros"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "comentario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.comentario",
                    ),
                ),
                (
                    "postagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.postagem",
                    ),
                ),
                (
                    "repositorio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.repositorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Arquivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=api.models.arquivo.arquivo_upload_path,
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "repositorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos",
                        to="api.repositorio",
                        verbose_name="Repositório",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="repositoriosFavoritados",
            field=models.ManyToManyField(
                blank=True,
                related_name="repositorios_favoritados",
                to="api.repositorio",
                verbose_name="Repositórios salvos",
            ),
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "data_solocitacao",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Data da solicitação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "pendente"),
                            ("reprovada", "reprovada"),
                            ("aprovada", "aprovada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
