# Generated by Django 5.2.4 on 2025-07-08 17:55

import api.models.arquivo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to=api.models.arquivo.arquivo_upload_path, verbose_name='Arquivo'),
        ),
    ]
