# Generated by Django 5.2.2 on 2025-07-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.postagem'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='repositorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.repositorio'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('ling', 'Linguajar Ofensivo'), ('spam', 'Spam'), ('out', 'Outros')], max_length=40),
        ),
    ]
