# Generated by Django 5.2.1 on 2025-05-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='seguidores',
        ),
    ]
