# Generated by Django 5.2.3 on 2025-07-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_arquivo_arquivo_alter_comentario_id'),
        ('api', '0003_solicitacao'),
    ]

    operations = [
    ]
