# Generated by Django 5.1.6 on 2025-05-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_comunidade_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('com', 'Comentário'), ('post', 'Postagem'), ('rep', 'Repositório')], max_length=4),
        ),
    ]
