# Generated by Django 5.2.1 on 2025-07-20 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_arquivo_arquivo_alter_comentario_id'),
        ('api', '0003_solicitacao'),
    ]

    operations = [
    ]
