# Generated by Django 5.1.6 on 2025-05-30 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_denuncia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('com', 'Comentário'), ('post', 'Postagem'), ('rep', 'Repositório')], max_length=40),
        ),
    ]
