# Generated by Django 5.2.4 on 2025-07-20 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_denuncia_comentario_alter_comentario_id_and_more'),
        ('api', '0004_merge_20250717_1110'),
    ]

    operations = [
    ]
