# Generated by Django 5.2.4 on 2025-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20250717_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d/', verbose_name='Banner'),
        ),
    ]
