# Generated by Django 5.1.6 on 2025-05-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_denuncia_tipo'),
    ]

    operations = [
    ]
