# Generated by Django 5.2.3 on 2025-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250719_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('ling', 'Linguajar Ofensivo'), ('spam', 'Spam'), ('dis', 'Discurso violento'), ('odio', 'Ódio'), ('out', 'Outros')], max_length=40),
        ),
    ]
