# Generated by Django 5.2.1 on 2025-07-22 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comunidade_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidade',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='comunidades_que_sigo', to=settings.AUTH_USER_MODEL, verbose_name='seguidores'),
        ),
    ]
