# Generated by Django 5.2.4 on 2025-07-27 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20250720_2006'),
        ('api', '0006_alter_denuncia_tipo'),
        ('api', '0006_comunidade_seguidores'),
    ]

    operations = [
    ]
