# Generated by Django 5.2.1 on 2025-05-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20250529_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='curtidas',
        ),
    ]
