# Generated by Django 5.2.1 on 2025-05-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_postagem_curtidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
