# Generated by Django 5.2.1 on 2025-05-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_postagem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
