# Generated by Django 5.2.3 on 2025-06-10 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_comunidade_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='api.categoria', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='comunidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comunidade', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imgPostagens/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
