# Generated by Django 5.2 on 2025-06-10 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_repositorio_categorias_repositorio_comunidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segue',
            field=models.ManyToManyField(blank=True, related_name='seguido_por', to=settings.AUTH_USER_MODEL, verbose_name='Segue'),
        ),
    ]
