# Generated by Django 5.2.4 on 2025-07-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_segue'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedinUrl',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
