# Generated by Django 5.2.2 on 2025-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_segue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
    ]
