# Generated by Django 5.2.1 on 2025-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usuario_segue'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedinUrl',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
