# Generated by Django 5.2.2 on 2025-07-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usuario_descricao'),
        ('api', '0012_usuario_banner_usuario_linkedinurl'),
    ]

    operations = [
    ]
