# Generated by Django 5.2.2 on 2025-07-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usuario_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/%d/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='linkedinUrl',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
    ]
