# Generated by Django 5.2.7 on 2025-10-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_denuncia_comentario_alter_comentario_id_and_more'),
        ('api', '0004_merge_20250720_2006'),
        ('api', '0013_merge_20250707_1121'),
    ]

    operations = [
    ]
