# Generated by Django 5.2.7 on 2025-10-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20251012_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('reprovada', 'reprovada'), ('aprovada', 'aprovada')], default='pendente', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(choices=[('ling', 'Linguajar Ofensivo'), ('spam', 'Spam'), ('dis', 'Discurso violento'), ('odio', 'Ódio'), ('out', 'Outros')], max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='papel',
            field=models.CharField(choices=[('mod', 'moderador'), ('int', 'internauta')], max_length=15, null=True, verbose_name='Papel'),
        ),
    ]
