apiVersion: apps/v1
kind: Deployment
metadata:
  name: bizzu-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bizzu-postgres
  template:
    metadata:
      labels:
        app: bizzu-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: bizzu-postgres-pvc
