# Generated by Django 4.2.11 on 2025-02-22 00:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('imagemPerfil', models.ImageField(null=True, upload_to='usuarios/%Y/%m/%d/', verbose_name='Imagem de perfil')),
                ('escolaFormacao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Escola de formação')),
                ('instituicaoAtual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Instituição atual')),
                ('localTrabalho', models.CharField(blank=True, max_length=30, null=True, verbose_name='Local de trabalho')),
                ('progressoCurso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Progresso no curso')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('tec', 'Tecnologia'), ('mat', 'Matéria'), ('per', 'Período')], max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='comunidade_imagens/', verbose_name='Imagem')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('anoFundacao', models.DateField(default=2025, verbose_name='Ano de fundação')),
                ('coordenacao', models.CharField(max_length=50, verbose_name='Coordenação')),
                ('linkPPC', models.URLField(verbose_name='Link ppc')),
                ('linkHorarios', models.URLField(verbose_name='Link horários')),
                ('linkExtra', models.URLField(verbose_name='Link extra')),
                ('seguidores', models.ManyToManyField(blank=True, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores')),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataPublicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categorias', models.ManyToManyField(blank=True, to='app_bizzu.categoria', verbose_name='Categorias')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bizzu.comunidade', verbose_name='Comunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositorios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Repositório',
                'verbose_name_plural': 'Repositórios',
            },
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de descrição')),
                ('imagem', models.ImageField(upload_to='imgPostagens/', verbose_name='Imagem')),
                ('dataPublicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação')),
                ('curtidas', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('categorias', models.ManyToManyField(blank=True, to='app_bizzu.categoria', verbose_name='Categorias')),
                ('comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bizzu.comunidade', verbose_name='Comunidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_curtida', to='app_bizzu.postagem', verbose_name='Postagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_curtida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('dataPostagem', models.DateTimeField(auto_now_add=True)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bizzu.postagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoRepositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='arquivosRepositorios/', verbose_name='Arquivo')),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app_bizzu.repositorio', verbose_name='Repositório')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='comunidades',
            field=models.ManyToManyField(blank=True, related_name='seguido_por', to='app_bizzu.comunidade', verbose_name='Comunidades'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='repositoriosFavoritados',
            field=models.ManyToManyField(blank=True, related_name='repositorios_favoritados', to='app_bizzu.repositorio', verbose_name='Repositórios salvos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='segue',
            field=models.ManyToManyField(blank=True, default=0, related_name='seguido_por', to=settings.AUTH_USER_MODEL, verbose_name='Segue'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, default=0, related_name='seguindo', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
