# Generated by Django 5.1.4 on 2025-01-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("tec", "Tecnologia"),
                            ("mat", "Matéria"),
                            ("per", "Período"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conteudo", models.CharField(max_length=300, verbose_name="Conteudo")),
                ("dataPostagem", models.DateTimeField(verbose_name="Data de postagem")),
            ],
        ),
        migrations.CreateModel(
            name="Postagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(max_length=200, verbose_name="Texto de descrição"),
                ),
                ("imagem", models.FileField(upload_to="", verbose_name="Imagem")),
                (
                    "dataPublicacao",
                    models.DateTimeField(verbose_name="Data de publicação"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repositorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataPublicacao",
                    models.DateTimeField(verbose_name="Data de publicação"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("titulo", models.CharField(max_length=50, verbose_name="Título")),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("username", models.CharField(max_length=20, verbose_name="Username")),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "escolaFormacao",
                    models.CharField(max_length=70, verbose_name="Escola de formação"),
                ),
                (
                    "instituicaoAtual",
                    models.CharField(max_length=70, verbose_name="Instituição atual"),
                ),
                (
                    "localTrabalho",
                    models.CharField(max_length=70, verbose_name="Local de trabalho"),
                ),
                (
                    "progressoCurso",
                    models.CharField(max_length=20, verbose_name="Progresso no curso"),
                ),
                (
                    "repositoriosFavoritados",
                    models.ManyToManyField(
                        related_name="repositoriosFavoritados",
                        to="app_bizzu.repositorio",
                        verbose_name="Repositórios salvos",
                    ),
                ),
                (
                    "seguidores",
                    models.ManyToManyField(
                        related_name="followes",
                        to="app_bizzu.usuario",
                        verbose_name="Seguidores",
                    ),
                ),
            ],
        ),
    ]
