# Generated by Django 5.1.4 on 2025-01-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                ("anoFundacao", models.DateField(verbose_name="Ano de fundação")),
                (
                    "coordenacao",
                    models.CharField(max_length=50, verbose_name="Coordenação"),
                ),
                ("linkPPC", models.URLField(verbose_name="Link ppc")),
                ("linkHorarios", models.URLField(verbose_name="Link horários")),
                ("linkExtra", models.URLField(verbose_name="Link extra")),
                (
                    "seguidores",
                    models.ManyToManyField(
                        related_name="follows",
                        to="app_bizzu.comunidade",
                        verbose_name="Seguidores",
                    ),
                ),
            ],
        ),
    ]
