# Generated by Django 5.1.5 on 2025-01-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0003_alter_postagem_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="postagem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comentarios",
                to="app_bizzu.postagem",
                verbose_name="Postagem",
            ),
        ),
        migrations.AddField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_bizzu.usuario",
                verbose_name="Usuário",
            ),
        ),
        migrations.AddField(
            model_name="comunidade",
            name="membros",
            field=models.ManyToManyField(
                related_name="comunidades",
                to="app_bizzu.usuario",
                verbose_name="Membros",
            ),
        ),
        migrations.AddField(
            model_name="postagem",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_bizzu.usuario",
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="dataPublicacao",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de publicação"
            ),
        ),
    ]
