# Generated by Django 5.0.3 on 2025-01-26 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0005_usuario_user_alter_usuario_repositoriosfavoritados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorio',
            name='arquivo',
            field=models.FileField(default=None, upload_to='', verbose_name='Arquivos anexados'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='comunidade',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bizzu.comunidade', verbose_name='Comunidade'),
        ),
        migrations.AddField(
            model_name='repositorio',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bizzu.usuario', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='dataPublicacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de publicação'),
        ),
    ]
