# Generated by Django 5.0.3 on 2025-01-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0006_repositorio_arquivo_repositorio_comunidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunidade',
            name='membros',
        ),
        migrations.AlterField(
            model_name='comunidade',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='follows', to='app_bizzu.usuario', verbose_name='Seguidores'),
        ),
    ]
