# Generated by Django 5.1.5 on 2025-01-26 18:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0007_remove_comunidade_membros_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="seguidores",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="user",
        ),
        migrations.AddField(
            model_name="usuario",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Criado em"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="imagemPerfil",
            field=models.ImageField(
                null=True,
                upload_to="usuarios/%Y/%m/%d/",
                verbose_name="Imagem de perfil",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(
                default="default_password", max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="escolaFormacao",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Escola de formação"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="instituicaoAtual",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Instituição atual"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="localTrabalho",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Local de trabalho"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="progressoCurso",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Progresso no curso"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="repositoriosFavoritados",
            field=models.ManyToManyField(
                blank=True,
                related_name="repositorios_favoritados",
                to="app_bizzu.repositorio",
                verbose_name="Repositórios salvos",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
