# Generated by Django 5.1.5 on 2025-01-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0008_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="nome",
            field=models.CharField(default="Admin", max_length=50, verbose_name="Nome"),
            preserve_default=False,
        ),
    ]
