# Generated by Django 5.1.5 on 2025-01-26 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0009_usuario_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="postagem",
            name="curtidas",
            field=models.IntegerField(default=0, verbose_name="Curtidas"),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="repositorio",
            name="arquivo",
            field=models.FileField(
                default=None,
                upload_to="arquivosRepositorios/",
                verbose_name="Arquivos anexados",
            ),
        ),
        migrations.CreateModel(
            name="Curtida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postagem_curtida",
                        to="app_bizzu.postagem",
                        verbose_name="Postagem",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuario_curtida",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
