# Generated by Django 5.1.5 on 2025-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0011_usuario_comunidades_usuarioseguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='anoFundacao',
            field=models.DateField(default=2025, verbose_name='Ano de fundação'),
        ),
    ]
