# Generated by Django 5.1.5 on 2025-01-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0013_alter_comunidade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
