# Generated by Django 5.1.5 on 2025-01-29 18:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0014_alter_comunidade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidade',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
