# Generated by Django 5.1.5 on 2025-02-03 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0016_usuario_segue_usuario_seguidores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segue',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='seguido_por', to=settings.AUTH_USER_MODEL, verbose_name='Segue'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='seguindo', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores'),
        ),
    ]
