# Generated by Django 5.1.5 on 2025-02-04 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0017_alter_usuario_segue_alter_usuario_seguidores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="conteudo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="dataPostagem",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="postagem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app_bizzu.postagem"
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
