# Generated by Django 4.2.11 on 2025-02-06 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0018_alter_comentario_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='segue',
            field=models.ManyToManyField(blank=True, default=0, related_name='seguido_por', to=settings.AUTH_USER_MODEL, verbose_name='Segue'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seguidores',
            field=models.ManyToManyField(blank=True, default=0, related_name='seguindo', to=settings.AUTH_USER_MODEL, verbose_name='Seguidores'),
        ),
    ]
