# Generated by Django 5.1.5 on 2025-02-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0020_comunidade_imagem_postagem_comunidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postagem",
            old_name="Comunidade",
            new_name="comunidade",
        ),
        migrations.AddField(
            model_name="postagem",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, to="app_bizzu.categoria", verbose_name="Categorias"
            ),
        ),
    ]
