# Generated by Django 5.1.5 on 2025-01-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0002_comunidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postagem",
            name="imagem",
            field=models.ImageField(upload_to="imgPostagens/", verbose_name="Imagem"),
        ),
    ]
