# Generated by Django 5.1.5 on 2025-01-25 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0004_comentario_postagem_comentario_usuario_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="repositoriosFavoritados",
            field=models.ManyToManyField(
                blank=True,
                related_name="repositoriosFavoritados",
                to="app_bizzu.repositorio",
                verbose_name="Repositórios salvos",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="seguidores",
            field=models.ManyToManyField(
                blank=True,
                related_name="followes",
                to="app_bizzu.usuario",
                verbose_name="Seguidores",
            ),
        ),
    ]
