# Generated by Django 5.1.5 on 2025-01-27 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bizzu', '0010_postagem_curtidas_alter_postagem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='comunidades',
            field=models.ManyToManyField(blank=True, related_name='membros', to='app_bizzu.comunidade', verbose_name='Comunidades'),
        ),
        migrations.CreateModel(
            name='UsuarioSeguidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to=settings.AUTH_USER_MODEL)),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
