# Generated by Django 5.1.5 on 2025-02-03 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0015_alter_comunidade_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="segue",
            field=models.ManyToManyField(
                default=0,
                related_name="seguido_por",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Segue",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="seguidores",
            field=models.ManyToManyField(
                default=0,
                related_name="seguindo",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Seguidores",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="comunidades",
            field=models.ManyToManyField(
                blank=True,
                related_name="seguido_por",
                to="app_bizzu.comunidade",
                verbose_name="Comunidades",
            ),
        ),
        migrations.DeleteModel(
            name="UsuarioSeguidores",
        ),
    ]
