# Generated by Django 5.1.5 on 2025-02-08 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0019_alter_usuario_segue_alter_usuario_seguidores"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidade",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="comunidade_imagens/",
                verbose_name="Imagem",
            ),
        ),
        migrations.AddField(
            model_name="postagem",
            name="Comunidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_bizzu.comunidade",
                verbose_name="Comunidade",
            ),
        ),
    ]
