# Generated by Django 5.1.5 on 2025-02-09 19:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_bizzu", "0021_rename_comunidade_postagem_comunidade_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postagem",
            options={"verbose_name": "Postagem", "verbose_name_plural": "Postagens"},
        ),
        migrations.AlterModelOptions(
            name="repositorio",
            options={
                "verbose_name": "Repositório",
                "verbose_name_plural": "Repositórios",
            },
        ),
        migrations.RemoveField(
            model_name="repositorio",
            name="arquivo",
        ),
        migrations.AddField(
            model_name="repositorio",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, to="app_bizzu.categoria", verbose_name="Categorias"
            ),
        ),
        migrations.AlterField(
            model_name="postagem",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="postagens",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="repositorio",
            name="comunidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_bizzu.comunidade",
                verbose_name="Comunidade",
            ),
        ),
        migrations.AlterField(
            model_name="repositorio",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="repositorio",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositorios",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ArquivoRepositorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="arquivosRepositorios/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "repositorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arquivos",
                        to="app_bizzu.repositorio",
                        verbose_name="Repositório",
                    ),
                ),
            ],
        ),
    ]
