name: Bizzu Frontend CI

on: 
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/front.yml"
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/front.yml"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar node 
        uses: actions/setup-node@v4
        with:
          node-version: 24
        
      - name: Instalar dependências 
        run: | 
          yarn install

      - name: Build do projeto
        run: |
          yarn build

